// AUTO-GENERATED by scripts/setup-ghl-iso-fields.ts — do not edit by hand.
// Target sub-account: 7gpshI6Ger307wy0gSRU
// Generated: 2026-05-07T18:59:43.285Z

import type { GHLFieldDef } from './ghl-fields'

export const GHL_FIELDS_ISO: Record<string, GHLFieldDef> = {
  utm_source: { id: 'PGJTGfRsDp4ZnBmINzVO', name: 'UTM Source', key: 'utm_source', type: 'TEXT' },
  campaign_name: { id: 'uzf5PgMaRV67z7IpI9kT', name: 'Campaign Name', key: 'campaign_name', type: 'TEXT' },
  ad_name: { id: 'PIWz9wyYpNE8YzgN8IrP', name: 'Ad Name', key: 'ad_name', type: 'TEXT' },
  fbclid: { id: 'c3HEuK4wMPoMxQP36Uzl', name: 'fbclid', key: 'fbclid', type: 'TEXT' },
  landing_page: { id: 'WmUBBdtaVnnrUA1A0jh3', name: 'Landing Page', key: 'landing_page', type: 'TEXT' },
  lead_source: { id: 'ckqcPkIu73xuG1OMkZzh', name: 'Lead Source', key: 'lead_source', type: 'TEXT' },
  ville: { id: 'EMvUAfCd1nfK92XOFwWg', name: 'Ville', key: 'ville', type: 'TEXT' },
  code_postal: { id: 'p6fMlu1tddxVmL4i0FSN', name: 'Code Postal', key: 'code_postal', type: 'TEXT' },
  latitude: { id: 'ZMWiwWMjby6YaJwncCj5', name: 'Latitude', key: 'latitude', type: 'TEXT' },
  longitude: { id: 'ws8VSXNw4b51F5dSuhx4', name: 'Longitude', key: 'longitude', type: 'TEXT' },
  province: { id: '7o3FvYluyCMQKB1zjFgV', name: 'Province', key: 'province', type: 'TEXT' },
  superficie_total: { id: 'jF5Z4GbAd3sU07GDn5sh', name: 'Superficie total', key: 'superficie_total', type: 'NUMERICAL' },
  hauteur_du_batiment: { id: 'Pgf8Y8PuZJrHyPC2i2kI', name: 'Hauteur du batiment', key: 'hauteur_du_batiment', type: 'NUMERICAL' },
  isolation_actuelle: { id: '9di5URhx4SplO59qhUCh', name: 'Isolation actuelle', key: 'isolation_actuelle', type: 'TEXT' },
  acces_entretoit: { id: 'xtFWNuPCvibxk3oc7eDR', name: 'Acces entretoit', key: 'acces_entretoit', type: 'TEXT' },
  systeme_de_chauffage: { id: 'MKyNDO2uDbGxYSbYp7qw', name: 'Systeme de chauffage', key: 'systeme_de_chauffage', type: 'TEXT' },
  problemes_identifies: { id: 'LWQ1sDv3KlJJxO3XpmDU', name: 'Problemes identifies', key: 'problemes_identifies', type: 'TEXT' },
  forme_du_toit: { id: 'E2QSWv69HkQJuas2o4bM', name: 'Forme du toit', key: 'forme_du_toit', type: 'TEXT' },
  complexite_pente: { id: '9sNa4ZxBmzClRrnqutJD', name: 'Complexite pente', key: 'complexite_pente', type: 'TEXT' },
  obstacles: { id: 'iBXckfYmOfTmBg3DiZL8', name: 'Obstacles', key: 'obstacles', type: 'TEXT' },
  nb_segments_toiture: { id: '9BewnDwPRCR4YB9AMdIQ', name: 'Nb segments toiture', key: 'nb_segments_toiture', type: 'NUMERICAL' },
  surface_utilisable: { id: 'Nruym6OYXwH0N5lC26GG', name: 'Surface utilisable', key: 'surface_utilisable', type: 'NUMERICAL' },
  difficulte_acces: { id: 'SZ47se1OmmZods3muSJR', name: 'Difficulte acces', key: 'difficulte_acces', type: 'TEXT' },
  econo__prix_min: { id: 'cWppmyPcMVWcVLwKxMCR', name: 'Econo - Prix min', key: 'econo__prix_min', type: 'NUMERICAL' },
  econo__prix_max: { id: 'Soof0hnOH7S8i6NUE0ce', name: 'Econo - Prix max', key: 'econo__prix_max', type: 'NUMERICAL' },
  standard__prix_min: { id: 'QpUhBlUPZzXONoEKdMIQ', name: 'Standard - Prix min', key: 'standard__prix_min', type: 'NUMERICAL' },
  standard__prix_max: { id: 'YcnckovWf0PTjDrMQQcN', name: 'Standard - Prix max', key: 'standard__prix_max', type: 'NUMERICAL' },
  premium__prix_min: { id: 'sAAdL21LGBrzhkM9F0XQ', name: 'Premium - Prix min', key: 'premium__prix_min', type: 'NUMERICAL' },
  premium__prix_max: { id: '2UI5mQyBd0XiVTgeUCOM', name: 'Premium - Prix max', key: 'premium__prix_max', type: 'NUMERICAL' },
  type_habitation: { id: 'gYP4OaxndoaSXgc1aN3Q', name: 'Type habitation', key: 'type_habitation', type: 'TEXT' },
  statut_proprietaire: { id: 'UNu3xqfPmSU5jlUA4sLp', name: 'Statut proprietaire', key: 'statut_proprietaire', type: 'TEXT' },
  eligible_subvention: { id: 'Y17HfEbVj0i4kzN4JPoz', name: 'Eligible subvention', key: 'eligible_subvention', type: 'TEXT' },
  // V2 funnel fields (Phase 2 will wire these into the payload).
  symptoms: { id: 'ZPE3HqwuNU2UFMPJoFLP', name: 'Symptoms', key: 'symptoms', type: 'TEXT' },
  hydro_bracket: { id: '09Yv7GFbSI63gpw2dnMS', name: 'Hydro Bracket', key: 'hydro_bracket', type: 'TEXT' },
  intent: { id: 'TXLCBATiEunuBmhBfiPk', name: 'Intent', key: 'intent', type: 'TEXT' },
} as const
